# Generated by Django 2.0.7 on 2018-12-09 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Posted On'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.CharField(choices=[('flag-o', 'flag-o'), ('play', 'play'), ('check', 'check'), ('times', 'times'), ('plus-circle', 'plus-circle')], max_length=20, verbose_name='Fontawesome Icon'),
        ),
    ]
