# Generated by Django 2.0.7 on 2018-12-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20181209_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='click_parameter',
            field=models.CharField(default='', max_length=10, verbose_name='View Parameter'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='click_view',
            field=models.CharField(max_length=100, verbose_name='View'),
        ),
    ]
