# Generated by Django 2.0.7 on 2018-12-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20181209_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='click_parameter',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='View Parameter'),
        ),
    ]
