# Generated by Django 2.0.7 on 2018-12-09 12:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='flow_definition',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='Flow Definition'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='openroad_uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='OpenROAD UUID'),
        ),
    ]
